from __future__ import annotations

from typing import Any, Dict, List

# Few-shot guidance for broad real-world question diversity.
# These examples guide planning only; runtime validation still enforces safety.
REPORT_PLANNER_FEW_SHOTS_VERSION = "planner_fs_v2026_02_19_now2"
REPORT_PLANNER_FEW_SHOTS: List[Dict[str, Any]] = [
    {
        "in": "Total payable amount as of today",
        "out": {
            "action": "run_report",
            "report_name": "Accounts Payable",
            "filters": {},
            "export": False,
            "needs_clarification": False,
            "post_transform": {"operation": "total", "params": {"column_hint": "Outstanding Amount"}},
        },
    },
    {
        "in": "Show AR aging for this month",
        "out": {
            "action": "run_report",
            "report_name": "Accounts Receivable",
            "filters": {},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "Top 5 customers by revenue in last month",
        "out": {
            "action": "run_report",
            "report_name": "Sales Analytics",
            "filters": {"tree_type": "Customer", "doc_type": "Sales Invoice"},
            "export": False,
            "needs_clarification": False,
            "post_transform": {"operation": "top_n", "params": {"n": 5, "column_hint": "Value"}},
        },
    },
    {
        "in": "Top 7 products by sold qty last month",
        "out": {
            "action": "run_report",
            "report_name": "Item-wise Sales Register",
            "filters": {},
            "export": False,
            "needs_clarification": False,
            "post_transform": {"operation": "top_n", "params": {"n": 7, "column_hint": "Qty"}},
        },
    },
    {
        "in": "Top 7 products by received qty last month",
        "out": {
            "action": "run_report",
            "report_name": "Purchase Analytics",
            "filters": {"tree_type": "Item", "doc_type": "Purchase Receipt"},
            "export": False,
            "needs_clarification": False,
            "post_transform": {"operation": "top_n", "params": {"n": 7, "column_hint": "Received Qty"}},
        },
    },
    {
        "in": "Sales by item this week, download excel",
        "out": {
            "action": "run_report",
            "report_name": "Sales Analytics",
            "filters": {"tree_type": "Item", "doc_type": "Sales Invoice"},
            "export": True,
            "needs_clarification": False,
        },
    },
    {
        "in": "Top 10 suppliers by purchase amount last month",
        "out": {
            "action": "run_report",
            "report_name": "Purchase Analytics",
            "filters": {"tree_type": "Supplier", "doc_type": "Purchase Invoice"},
            "export": False,
            "needs_clarification": False,
            "post_transform": {"operation": "top_n", "params": {"n": 10, "column_hint": "Value"}},
        },
    },
    {
        "in": "Top 10 customers by outstanding receivable as of today",
        "out": {
            "action": "run_report",
            "report_name": "Accounts Receivable",
            "filters": {},
            "export": False,
            "needs_clarification": False,
            "post_transform": {"operation": "top_n", "params": {"n": 10, "column_hint": "Outstanding Amount"}},
        },
    },
    {
        "in": "Top 10 suppliers by outstanding payable as of today",
        "out": {
            "action": "run_report",
            "report_name": "Accounts Payable",
            "filters": {},
            "export": False,
            "needs_clarification": False,
            "post_transform": {"operation": "top_n", "params": {"n": 10, "column_hint": "Outstanding Amount"}},
        },
    },
    {
        "in": "Show receivable aging for customer ABC as of today",
        "out": {
            "action": "run_report",
            "report_name": "Accounts Receivable",
            "filters": {"customer": "ABC"},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "Show payable aging for supplier XYZ as of today",
        "out": {
            "action": "run_report",
            "report_name": "Accounts Payable",
            "filters": {"supplier": "XYZ"},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "Show sales trend by month this year",
        "out": {
            "action": "run_report",
            "report_name": "Sales Analytics",
            "filters": {"tree_type": "Customer", "doc_type": "Sales Invoice"},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "Show purchase trend by month this year",
        "out": {
            "action": "run_report",
            "report_name": "Purchase Analytics",
            "filters": {"tree_type": "Supplier", "doc_type": "Purchase Invoice"},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "Sales by item this week, download excel",
        "out": {
            "action": "run_report",
            "report_name": "Sales Analytics",
            "filters": {"tree_type": "Item", "doc_type": "Sales Invoice"},
            "export": True,
            "needs_clarification": False,
        },
    },
    {
        "in": "Show sales register for customer ABC last month",
        "out": {
            "action": "run_report",
            "report_name": "Sales Register",
            "filters": {"customer": "ABC"},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "Show purchase register for supplier XYZ last month",
        "out": {
            "action": "run_report",
            "report_name": "Purchase Register",
            "filters": {"supplier": "XYZ"},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "Show general ledger for account Cash this month",
        "out": {
            "action": "run_report",
            "report_name": "General Ledger",
            "filters": {"account": "Cash"},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "Stock balance in Yangon Main Warehouse",
        "out": {
            "action": "run_report",
            "report_name": "Warehouse Wise Stock Balance",
            "filters": {"warehouse": "Yangon Main Warehouse"},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "Show stock balance by warehouse and export to xlsx",
        "out": {
            "action": "run_report",
            "report_name": "Warehouse Wise Stock Balance",
            "filters": {},
            "export": True,
            "needs_clarification": False,
        },
    },
    {
        "in": "Show stock balance as of today in warehouse MMOB",
        "out": {
            "action": "run_report",
            "report_name": "Stock Balance",
            "filters": {"warehouse": "MMOB"},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "Show stock valuation by item in company ACME",
        "out": {
            "action": "run_report",
            "report_name": "Stock Balance",
            "filters": {"company": "ACME"},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "Which employee has attendance issues this month?",
        "out": {
            "action": "run_report",
            "report_name": "Monthly Attendance Sheet",
            "filters": {},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "What are the open material requests for production",
        "out": {
            "action": "run_report",
            "report_name": "Material Request",
            "filters": {},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "Create a draft sales order for customer ABC with item ITEM-001 qty 2",
        "out": {
            "action": "write_draft",
            "doctype": "Sales Order",
            "operation": "create",
            "payload": {"customer": "ABC", "items": [{"item_code": "ITEM-001", "qty": 2}]},
            "confirmation_text": "Create draft Sales Order for customer ABC with ITEM-001 qty 2?",
        },
    },
    {
        "in": "Cancel purchase invoice PINV-0001",
        "out": {
            "action": "write_draft",
            "doctype": "Purchase Invoice",
            "operation": "cancel",
            "payload": {"name": "PINV-0001"},
            "confirmation_text": "Cancel Purchase Invoice PINV-0001?",
        },
    },
    {
        "in": "Total outstanding amount",
        "out": {"action": "transform_last", "operation": "total", "params": {"column_hint": "Outstanding Amount"}},
    },
    {
        "in": "Show top 10 of that by amount",
        "out": {"action": "transform_last", "operation": "top_n", "params": {"n": 10, "column_hint": "Amount"}},
    },
    {
        "in": "Sort that by outstanding amount descending",
        "out": {"action": "transform_last", "operation": "sort", "params": {"column_hint": "Outstanding Amount", "direction": "desc"}},
    },
    {
        "in": "Show as million",
        "out": {"action": "transform_last", "operation": "summary", "params": {"scale_unit": "million"}},
    },
    {
        "in": "Display that in thousand",
        "out": {"action": "transform_last", "operation": "summary", "params": {"scale_unit": "thousand"}},
    },
    {
        "in": "Filter that to customer containing abc",
        "out": {"action": "transform_last", "operation": "filter", "params": {"column_hint": "Customer", "operator": "contains", "value": "abc"}},
    },
    {
        "in": "Give me a summary of that",
        "out": {"action": "transform_last", "operation": "summary", "params": {"column_hint": "Outstanding Amount"}},
    },
    {
        "in": "Show receivables by customer for the same period",
        "out": {
            "action": "run_report",
            "report_name": "Accounts Receivable",
            "filters": {},
            "export": False,
            "needs_clarification": False,
        },
    },
    {
        "in": "Show stock balance in warehouse MMOB",
        "out": {
            "action": "clarify",
            "report_name": "Stock Balance",
            "filters_so_far": {"warehouse": "MMOB"},
            "ask": {"question": "I found multiple warehouses matching MMOB. Which exact warehouse should I use?"},
            "needs_clarification": True,
            "export": False,
        },
    },
    {
        "in": "Show invoice details for INV-XXXX-UNKNOWN",
        "out": {
            "action": "clarify",
            "report_name": "",
            "filters_so_far": {"name": "INV-XXXX-UNKNOWN"},
            "ask": {"question": "I could not find that invoice. Please provide a valid invoice ID."},
            "needs_clarification": True,
            "export": False,
        },
    },
    {
        "in": "Show margin by campaign and warehouse age bucket",
        "out": {
            "action": "clarify",
            "report_name": "",
            "filters_so_far": {},
            "ask": {"question": "Which business goal should I prioritize first: sales margin by campaign or stock age by warehouse?"},
            "needs_clarification": True,
            "export": False,
        },
    },
    {
        "in": "Can you clarify first, I need only one branch",
        "out": {
            "action": "clarify",
            "report_name": "",
            "filters_so_far": {},
            "ask": {"question": "Which company or branch should I use?"},
            "needs_clarification": True,
            "export": False,
        },
    },
]


BUSINESS_REQUEST_SPEC_FEW_SHOTS_VERSION = "spec_fs_v2026_02_19_now2"
BUSINESS_REQUEST_SPEC_FEW_SHOTS: List[Dict[str, Any]] = [
    {
        "in": "Top 5 customers by revenue last month",
        "out": {
            "intent": "READ",
            "task_type": "ranking",
            "subject": "customers",
            "metric": "revenue",
            "aggregation": "sum",
            "group_by": ["customer"],
            "time_scope": {"mode": "relative", "value": "last_month"},
            "filters": {},
            "top_n": 5,
            "output_contract": {"mode": "top_n", "minimal_columns": ["customer", "revenue"]},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "Top 7 products by sold qty last month",
        "out": {
            "intent": "READ",
            "task_type": "ranking",
            "subject": "products",
            "metric": "sold quantity",
            "aggregation": "sum",
            "group_by": ["item"],
            "time_scope": {"mode": "relative", "value": "last_month"},
            "filters": {},
            "top_n": 7,
            "output_contract": {"mode": "top_n", "minimal_columns": ["item", "sold quantity"]},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "Top 7 products by received qty last month",
        "out": {
            "intent": "READ",
            "task_type": "ranking",
            "subject": "products",
            "metric": "received quantity",
            "aggregation": "sum",
            "group_by": ["item"],
            "time_scope": {"mode": "relative", "value": "last_month"},
            "filters": {},
            "top_n": 7,
            "output_contract": {"mode": "top_n", "minimal_columns": ["item", "received quantity"]},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "Top 10 suppliers by purchase amount last month",
        "out": {
            "intent": "READ",
            "task_type": "ranking",
            "subject": "suppliers",
            "metric": "purchase amount",
            "aggregation": "sum",
            "group_by": ["supplier"],
            "time_scope": {"mode": "relative", "value": "last_month"},
            "filters": {},
            "top_n": 10,
            "output_contract": {"mode": "top_n", "minimal_columns": ["supplier", "purchase amount"]},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "Total receivable as of today",
        "out": {
            "intent": "READ",
            "task_type": "kpi",
            "subject": "accounts receivable",
            "metric": "outstanding amount",
            "aggregation": "sum",
            "group_by": [],
            "time_scope": {"mode": "as_of", "value": "today"},
            "filters": {},
            "top_n": 0,
            "output_contract": {"mode": "kpi", "minimal_columns": ["outstanding amount"]},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "Total payable as of today",
        "out": {
            "intent": "READ",
            "task_type": "kpi",
            "subject": "accounts payable",
            "metric": "outstanding amount",
            "aggregation": "sum",
            "group_by": [],
            "time_scope": {"mode": "as_of", "value": "today"},
            "filters": {},
            "top_n": 0,
            "output_contract": {"mode": "kpi", "minimal_columns": ["outstanding amount"]},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "Show stock balance in warehouse MMOB",
        "out": {
            "intent": "READ",
            "task_type": "detail",
            "subject": "stock balance",
            "metric": "stock balance",
            "aggregation": "none",
            "group_by": [],
            "time_scope": {"mode": "none", "value": ""},
            "filters": {"warehouse": "MMOB"},
            "top_n": 0,
            "output_contract": {"mode": "detail", "minimal_columns": ["warehouse", "stock balance"]},
            "ambiguities": ["warehouse_match"],
            "needs_clarification": True,
            "clarification_question": "I found multiple warehouses matching MMOB. Which exact warehouse should I use?",
        },
    },
    {
        "in": "Show stock balance in Yangon Main Warehouse",
        "out": {
            "intent": "READ",
            "task_type": "detail",
            "subject": "stock balance",
            "metric": "stock balance",
            "aggregation": "none",
            "group_by": [],
            "time_scope": {"mode": "none", "value": ""},
            "filters": {"warehouse": "Yangon Main Warehouse"},
            "top_n": 0,
            "output_contract": {"mode": "detail", "minimal_columns": ["warehouse", "stock balance"]},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "Show sales register for customer ABC last month",
        "out": {
            "intent": "READ",
            "task_type": "detail",
            "subject": "sales invoices",
            "metric": "",
            "aggregation": "none",
            "group_by": [],
            "time_scope": {"mode": "relative", "value": "last_month"},
            "filters": {"customer": "ABC"},
            "top_n": 0,
            "output_contract": {"mode": "detail", "minimal_columns": ["name", "customer", "posting date", "grand total"]},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "I mean receivable, not payable",
        "out": {
            "intent": "READ",
            "task_type": "detail",
            "subject": "accounts receivable",
            "metric": "outstanding amount",
            "aggregation": "sum",
            "group_by": ["customer"],
            "time_scope": {"mode": "as_of", "value": "today"},
            "filters": {},
            "top_n": 0,
            "output_contract": {"mode": "detail", "minimal_columns": ["customer", "outstanding amount"]},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "Create draft sales order for customer ABC item ITEM-001 qty 2",
        "out": {
            "intent": "WRITE_DRAFT",
            "task_type": "detail",
            "subject": "sales order",
            "metric": "",
            "aggregation": "none",
            "group_by": [],
            "time_scope": {"mode": "none", "value": ""},
            "filters": {"customer": "ABC", "item_code": "ITEM-001"},
            "top_n": 0,
            "output_contract": {"mode": "detail", "minimal_columns": []},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "I mean sold qty, not received qty",
        "out": {
            "intent": "READ",
            "task_type": "ranking",
            "subject": "products",
            "metric": "sold quantity",
            "aggregation": "sum",
            "group_by": ["item"],
            "time_scope": {"mode": "relative", "value": "last_month"},
            "filters": {},
            "top_n": 7,
            "output_contract": {"mode": "top_n", "minimal_columns": ["item", "sold quantity"]},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "Show total receivable amount as of today, show as million",
        "out": {
            "intent": "READ",
            "task_type": "kpi",
            "subject": "accounts receivable",
            "metric": "outstanding amount",
            "aggregation": "sum",
            "group_by": [],
            "time_scope": {"mode": "as_of", "value": "today"},
            "filters": {},
            "top_n": 0,
            "output_contract": {"mode": "kpi", "minimal_columns": ["outstanding amount"]},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "Show only top 10 from that",
        "out": {
            "intent": "TRANSFORM",
            "task_type": "ranking",
            "subject": "",
            "metric": "",
            "aggregation": "none",
            "group_by": [],
            "time_scope": {"mode": "none", "value": ""},
            "filters": {},
            "top_n": 10,
            "output_contract": {"mode": "top_n", "minimal_columns": []},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "Sort that by amount descending",
        "out": {
            "intent": "TRANSFORM",
            "task_type": "detail",
            "subject": "",
            "metric": "amount",
            "aggregation": "none",
            "group_by": [],
            "time_scope": {"mode": "none", "value": ""},
            "filters": {},
            "top_n": 0,
            "output_contract": {"mode": "detail", "minimal_columns": []},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
    {
        "in": "Show as million",
        "out": {
            "intent": "TRANSFORM",
            "task_type": "kpi",
            "subject": "",
            "metric": "",
            "aggregation": "none",
            "group_by": [],
            "time_scope": {"mode": "none", "value": ""},
            "filters": {},
            "top_n": 0,
            "output_contract": {"mode": "kpi", "minimal_columns": []},
            "ambiguities": [],
            "needs_clarification": False,
            "clarification_question": "",
        },
    },
]
