#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGE="${ERPW_PLAYWRIGHT_IMAGE:-mcr.microsoft.com/playwright:v1.59.1-noble}"
NETWORK="${ERPW_PLAYWRIGHT_DOCKER_NETWORK:-host}"

if ! command -v docker >/dev/null 2>&1; then
	echo "Docker is required to run the isolated Playwright smoke runner." >&2
	exit 1
fi

if [ "$#" -gt 0 ]; then
	SMOKE_COMMAND="$*"
else
	SMOKE_COMMAND="npm run test:roles && npm run test:sales-order-analysis"
fi

EXTRA_DOCKER_ARGS=()
if [ -n "${ERPW_PLAYWRIGHT_ARTIFACT_ROOT:-}" ]; then
	mkdir -p "$ERPW_PLAYWRIGHT_ARTIFACT_ROOT"
	EXTRA_DOCKER_ARGS+=(-v "$ERPW_PLAYWRIGHT_ARTIFACT_ROOT:/freeze-artifacts")
fi

DOCKER_PROCUREMENT_PHASE7J2C_ASSET_ROOT="${ERPW_PROCUREMENT_PHASE7J2C_ASSET_ROOT:-}"
if [ -n "${ERPW_PROCUREMENT_PHASE7J2C_ASSET_ROOT:-}" ]; then
	EXTRA_DOCKER_ARGS+=(-v "$ERPW_PROCUREMENT_PHASE7J2C_ASSET_ROOT:/phase7j2c-assets:ro")
	DOCKER_PROCUREMENT_PHASE7J2C_ASSET_ROOT="/phase7j2c-assets"
fi

DOCKER_PROCUREMENT_PHASE7K_ASSET_ROOT="${ERPW_PROCUREMENT_PHASE7K_ASSET_ROOT:-}"
if [ -n "${ERPW_PROCUREMENT_PHASE7K_ASSET_ROOT:-}" ]; then
	EXTRA_DOCKER_ARGS+=(-v "$ERPW_PROCUREMENT_PHASE7K_ASSET_ROOT:/phase7k-assets:ro")
	DOCKER_PROCUREMENT_PHASE7K_ASSET_ROOT="/phase7k-assets"
fi

DOCKER_PROCUREMENT_PHASE7L_ASSET_ROOT="${ERPW_PROCUREMENT_PHASE7L_ASSET_ROOT:-}"
if [ -n "${ERPW_PROCUREMENT_PHASE7L_ASSET_ROOT:-}" ]; then
	EXTRA_DOCKER_ARGS+=(-v "$ERPW_PROCUREMENT_PHASE7L_ASSET_ROOT:/phase7l-assets:ro")
	DOCKER_PROCUREMENT_PHASE7L_ASSET_ROOT="/phase7l-assets"
fi

DOCKER_WAREHOUSE_W3_ASSET_ROOT="${ERPW_WAREHOUSE_W3_ASSET_ROOT:-}"
if [ -n "${ERPW_WAREHOUSE_W3_ASSET_ROOT:-}" ]; then
	EXTRA_DOCKER_ARGS+=(-v "${ERPW_WAREHOUSE_W3_ASSET_ROOT}:/warehouse-w3-assets:ro")
	DOCKER_WAREHOUSE_W3_ASSET_ROOT="/warehouse-w3-assets"
fi

DOCKER_WAREHOUSE_W3A_ASSET_ROOT="${ERPW_WAREHOUSE_W3A_ASSET_ROOT:-}"
if [ -n "${ERPW_WAREHOUSE_W3A_ASSET_ROOT:-}" ]; then
	EXTRA_DOCKER_ARGS+=(-v "${ERPW_WAREHOUSE_W3A_ASSET_ROOT}:/warehouse-w3a-assets:ro")
	DOCKER_WAREHOUSE_W3A_ASSET_ROOT="/warehouse-w3a-assets"
fi

DOCKER_WAREHOUSE_W4A_ASSET_ROOT="${ERPW_WAREHOUSE_W4A_ASSET_ROOT:-}"
if [ -n "${ERPW_WAREHOUSE_W4A_ASSET_ROOT:-}" ]; then
	EXTRA_DOCKER_ARGS+=(-v "${ERPW_WAREHOUSE_W4A_ASSET_ROOT}:/warehouse-w4a-assets:ro")
	DOCKER_WAREHOUSE_W4A_ASSET_ROOT="/warehouse-w4a-assets"
fi

DOCKER_WAREHOUSE_W4B_ASSET_ROOT="${ERPW_WAREHOUSE_W4B_ASSET_ROOT:-}"
if [ -n "${ERPW_WAREHOUSE_W4B_ASSET_ROOT:-}" ]; then
	EXTRA_DOCKER_ARGS+=(-v "${ERPW_WAREHOUSE_W4B_ASSET_ROOT}:/warehouse-w4b-assets:ro")
	DOCKER_WAREHOUSE_W4B_ASSET_ROOT="/warehouse-w4b-assets"
fi

DOCKER_WAREHOUSE_W5A_ASSET_ROOT="${ERPW_WAREHOUSE_W5A_ASSET_ROOT:-}"
if [ -n "${ERPW_WAREHOUSE_W5A_ASSET_ROOT:-}" ]; then
	EXTRA_DOCKER_ARGS+=(-v "${ERPW_WAREHOUSE_W5A_ASSET_ROOT}:/warehouse-w5a-assets:ro")
	DOCKER_WAREHOUSE_W5A_ASSET_ROOT="/warehouse-w5a-assets"
fi

DOCKER_WAREHOUSE_W5B_ASSET_ROOT="${ERPW_WAREHOUSE_W5B_ASSET_ROOT:-}"
if [ -n "${ERPW_WAREHOUSE_W5B_ASSET_ROOT:-}" ]; then
	EXTRA_DOCKER_ARGS+=(-v "${ERPW_WAREHOUSE_W5B_ASSET_ROOT}:/warehouse-w5b-assets:ro")
	DOCKER_WAREHOUSE_W5B_ASSET_ROOT="/warehouse-w5b-assets"
fi

DOCKER_WAREHOUSE_W6A_ASSET_ROOT="${ERPW_WAREHOUSE_W6A_ASSET_ROOT:-}"
if [ -n "${ERPW_WAREHOUSE_W6A_ASSET_ROOT:-}" ]; then
	EXTRA_DOCKER_ARGS+=(-v "${ERPW_WAREHOUSE_W6A_ASSET_ROOT}:/warehouse-w6a-assets:ro")
	DOCKER_WAREHOUSE_W6A_ASSET_ROOT="/warehouse-w6a-assets"
fi

DOCKER_WAREHOUSE_W6B_ASSET_ROOT="${ERPW_WAREHOUSE_W6B_ASSET_ROOT:-}"
if [ -n "${ERPW_WAREHOUSE_W6B_ASSET_ROOT:-}" ]; then
	EXTRA_DOCKER_ARGS+=(-v "${ERPW_WAREHOUSE_W6B_ASSET_ROOT}:/warehouse-w6b-assets:ro")
	DOCKER_WAREHOUSE_W6B_ASSET_ROOT="/warehouse-w6b-assets"
fi

mkdir -p "$SCRIPT_DIR/artifacts" "$SCRIPT_DIR/test-results"

docker run --rm \
	--network "$NETWORK" \
	-v "$SCRIPT_DIR:/work" \
	"${EXTRA_DOCKER_ARGS[@]}" \
	-w /work \
	-e CI="${CI:-1}" \
	-e ERPW_BASE_URL \
	-e ERPW_MANAGER_USERNAME \
	-e ERPW_MANAGER_PASSWORD \
	-e ERPW_USER_USERNAME \
	-e ERPW_USER_PASSWORD \
	-e ERPW_PURCHASE_MANAGER_USERNAME \
	-e ERPW_PURCHASE_MANAGER_PASSWORD \
	-e ERPW_PURCHASE_USER_USERNAME \
	-e ERPW_PURCHASE_USER_PASSWORD \
	-e ERPW_USERNAME \
	-e ERPW_PASSWORD \
	-e ERPW_SESSION_SID \
	-e ERPW_HEADLESS \
	-e ERPW_REPORT_SHELL_VERSION \
	-e ERPW_ROLE_SMOKE_OUT \
	-e ERPW_SALES_ACTIONS_OUT \
	-e ERPW_SALES_WORKLISTS_OUT \
	-e ERPW_SALES_PERFORMANCE_OUT \
	-e ERPW_SALES_DIRECTORY_API_THRESHOLD_MS \
	-e ERPW_SALES_DIRECTORY_PERF_SAMPLES \
	-e ERPW_SALES_DETAIL_OUT \
	-e ERPW_SALES_REPORTS_OUT \
	-e ERPW_SALES_LEAKAGE_OUT \
	-e ERPW_SALES_VISUAL_OUT \
	-e ERPW_SALES_ORDER_ANALYSIS_OUT \
	-e ERPW_SALES_ORDER_ANALYSIS_FROM \
	-e ERPW_SALES_ORDER_ANALYSIS_TO \
	-e ERPW_SALES_ORDER_NAME \
	-e ERPW_SALES_ORDER_ROUTE \
	-e ERPW_QUOTATION_NAME \
	-e ERPW_QUOTATION_ROUTE \
	-e ERPW_DELIVERY_NOTE_NAME \
	-e ERPW_DELIVERY_NOTE_ROUTE \
	-e ERPW_SALES_INVOICE_NAME \
	-e ERPW_SALES_INVOICE_ROUTE \
	-e ERPW_CAPTURE_REFERENCE \
	-e ERPW_CAPTURE_ROOT \
	-e ERPW_PROCUREMENT_PHASE5C_ARTIFACT_DIR \
	-e ERPW_PROCUREMENT_PHASE6C2A_ARTIFACT_DIR \
	-e ERPW_PROCUREMENT_PHASE7E1A_ARTIFACT_DIR \
	-e ERPW_PROCUREMENT_PHASE7J1B_ARTIFACT_DIR \
	-e ERPW_PROCUREMENT_PHASE7J1B_PERFORMANCE_OUT \
	-e ERPW_PROCUREMENT_PHASE7J1B_ASSET_ROOT \
	-e ERPW_PROCUREMENT_PHASE7J1B_EXPECT_ASYNC \
	-e ERPW_PROCUREMENT_PHASE7J1B_FIRST_USEFUL_TARGET_MS \
	-e ERPW_PROCUREMENT_PHASE7J1B_BOOTSTRAP_TARGET_MS \
	-e ERPW_PROCUREMENT_PHASE7J1B_READINESS_SAMPLES \
	-e ERPW_PROCUREMENT_PHASE7J1B_READINESS_TARGET_MS \
	-e ERPW_PROCUREMENT_PHASE7J1B_READINESS_MAX_MS \
	-e ERPW_PROCUREMENT_PHASE7J2C_ARTIFACT_DIR \
	-e ERPW_PROCUREMENT_PHASE7J2C_ASSET_ROOT="$DOCKER_PROCUREMENT_PHASE7J2C_ASSET_ROOT" \
	-e ERPW_PROCUREMENT_PHASE7K_ARTIFACT_DIR \
	-e ERPW_PROCUREMENT_PHASE7K_ASSET_ROOT="$DOCKER_PROCUREMENT_PHASE7K_ASSET_ROOT" \
	-e ERPW_PROCUREMENT_PHASE7L_ARTIFACT_DIR \
	-e ERPW_PROCUREMENT_PHASE7L_ASSET_ROOT="$DOCKER_PROCUREMENT_PHASE7L_ASSET_ROOT" \
	-e ERPW_PROCUREMENT_DETAIL_PERFORMANCE_OUT \
	-e ERPW_PROCUREMENT_DETAIL_ASSET_ROOT \
	-e ERPW_PROCUREMENT_DETAIL_API_THRESHOLD \
	-e ERPW_PROCUREMENT_DETAIL_CONTEXT_CALL_THRESHOLD \
	-e ERPW_PROCUREMENT_DETAIL_READY_THRESHOLD_MS \
	-e ERPW_PROCUREMENT_SUPPLIER_NAME \
	-e ERPW_PROCUREMENT_ITEM_CODE \
	-e ERPW_PROCUREMENT_PURCHASE_ORDER \
	-e ERPW_WAREHOUSE_MANAGER_USERNAME \
	-e ERPW_WAREHOUSE_MANAGER_PASSWORD \
	-e ERPW_STOCK_MANAGER_USERNAME \
	-e ERPW_STOCK_MANAGER_PASSWORD \
	-e ERPW_WAREHOUSE_USER_USERNAME \
	-e ERPW_WAREHOUSE_USER_PASSWORD \
	-e ERPW_STOCK_USER_USERNAME \
	-e ERPW_STOCK_USER_PASSWORD \
	-e ERPW_WAREHOUSE_W3_ARTIFACT_DIR \
	-e ERPW_WAREHOUSE_W3_ASSET_ROOT="$DOCKER_WAREHOUSE_W3_ASSET_ROOT" \
	-e ERPW_WAREHOUSE_W3_TIMEOUT \
	-e ERPW_WAREHOUSE_W3_WARM_TARGET_MS \
	-e ERPW_WAREHOUSE_W3A_ARTIFACT_DIR \
	-e ERPW_WAREHOUSE_W3A_ASSET_ROOT="$DOCKER_WAREHOUSE_W3A_ASSET_ROOT" \
	-e ERPW_WAREHOUSE_W3A_TIMEOUT \
	-e ERPW_WAREHOUSE_W4A_ARTIFACT_DIR \
	-e ERPW_WAREHOUSE_W4A_ASSET_ROOT="$DOCKER_WAREHOUSE_W4A_ASSET_ROOT" \
	-e ERPW_WAREHOUSE_W4A_TIMEOUT \
	-e ERPW_WAREHOUSE_W4A_WARM_TARGET_MS \
	-e ERPW_WAREHOUSE_W4B_ARTIFACT_DIR \
	-e ERPW_WAREHOUSE_W4B_ASSET_ROOT="$DOCKER_WAREHOUSE_W4B_ASSET_ROOT" \
	-e ERPW_WAREHOUSE_W4B_TIMEOUT \
	-e ERPW_WAREHOUSE_W4B_WARM_TARGET_MS \
	-e ERPW_WAREHOUSE_W5A_ARTIFACT_DIR \
	-e ERPW_WAREHOUSE_W5A_ASSET_ROOT="$DOCKER_WAREHOUSE_W5A_ASSET_ROOT" \
	-e ERPW_WAREHOUSE_W5A_TIMEOUT \
	-e ERPW_WAREHOUSE_W5A_WARM_TARGET_MS \
	-e ERPW_WAREHOUSE_W5B_ARTIFACT_DIR \
	-e ERPW_WAREHOUSE_W5B_ASSET_ROOT="$DOCKER_WAREHOUSE_W5B_ASSET_ROOT" \
	-e ERPW_WAREHOUSE_W5B_TIMEOUT \
	-e ERPW_WAREHOUSE_W5B_WARM_TARGET_MS \
	-e ERPW_WAREHOUSE_W6A_ARTIFACT_DIR \
	-e ERPW_WAREHOUSE_W6A_ASSET_ROOT="$DOCKER_WAREHOUSE_W6A_ASSET_ROOT" \
	-e ERPW_WAREHOUSE_W6A_TIMEOUT \
	-e ERPW_WAREHOUSE_W6B_ARTIFACT_DIR \
	-e ERPW_WAREHOUSE_W6B_ASSET_ROOT="$DOCKER_WAREHOUSE_W6B_ASSET_ROOT" \
	-e ERPW_WAREHOUSE_W6B_TIMEOUT \
	-e ERPW_SYSTEM_MANAGER_USERNAME \
	-e ERPW_SYSTEM_MANAGER_PASSWORD \
	-e ERPW_ADMIN_USERNAME \
	-e ERPW_ADMIN_PASSWORD \
	-e ERPW_SALES_CONSOLE_ROUTE \
	"$IMAGE" \
	bash -lc "set -euo pipefail; rm -rf /tmp/erpw-ui-smoke; mkdir -p /tmp/erpw-ui-smoke; tar --exclude='./node_modules' --exclude='./test-results' -cf - -C /work . | tar -xf - -C /tmp/erpw-ui-smoke; cd /tmp/erpw-ui-smoke; npm ci && ${SMOKE_COMMAND}"
